import React, {useState} from 'react';
import runIndex from './runs/index.json';
import styles from './simulator.module.css';

type RunResult = (typeof runIndex.runs)[number];
type WeekResult = RunResult['weeks'][number];
type MetricKey = keyof WeekResult;

const series: Array<{key: MetricKey; label: string; color: string}> = [
  {key: 'aware', label: 'Aware', color: '#42a5f5'},
  {key: 'training', label: 'In training', color: '#ffb74d'},
  {key: 'trained', label: 'Trained', color: '#ab7df6'},
  {key: 'employed', label: 'Employed', color: '#5ee6b8'},
];

function pathFor(results: WeekResult[], key: MetricKey, population: number): string {
  return results.map((row, index) => {
    const x = (index / (results.length - 1)) * 100;
    const y = 100 - (Number(row[key]) / population) * 100;
    return `${index === 0 ? 'M' : 'L'} ${x.toFixed(2)} ${y.toFixed(2)}`;
  }).join(' ');
}

export default function CityOpportunitySimulator(): React.JSX.Element {
  const [scenarioId, setScenarioId] = useState('baseline');
  const scenario = runIndex.runs.find((candidate) => candidate.scenario_id === scenarioId)!;
  const {config, metrics, weeks, artifacts, run_id} = scenario;

  return <div className={styles.simulator} data-testid="city-opportunity-simulator">
    <div className={styles.header}><div><span>MESA {runIndex.engine.version} RUNS · SEED {config.seed}</span><h2>Budget → awareness → skills → work</h2></div><button type="button" onClick={() => setScenarioId('baseline')}>Reset model</button></div>
    <div className={styles.scenarios} data-testid="simulation-controls">
      {runIndex.runs.map((candidate) => <button key={candidate.scenario_id} type="button" aria-pressed={candidate.scenario_id === scenarioId} onClick={() => setScenarioId(candidate.scenario_id)}>{candidate.label}</button>)}
    </div>
    <div className={styles.configuration}>
      <span>Budget <strong>${config.budget / 1000}k</strong></span><span>Outreach <strong>{Math.round(config.outreach_rate * 100)}%</strong></span><span>Training seats <strong>{config.training_seats}</strong></span><span>Openings <strong>{config.job_openings}</strong></span><span>Run folder <strong>{run_id}</strong></span>
    </div>
    <div className={styles.metrics} data-testid="simulation-results">
      <div><span>Residents reached</span><strong>{metrics.residentsReached}</strong><small>{Math.round((metrics.residentsReached / config.population) * 100)}% of population</small></div>
      <div><span>Completed training</span><strong>{metrics.completedTraining}</strong><small>{weeks.at(-1)!.training} still enrolled</small></div>
      <div><span>Employed</span><strong>{metrics.employed}</strong><small>{Math.round((metrics.employed / config.population) * 100)}% of population</small></div>
      <div><span>Budget remaining</span><strong>${Math.round(metrics.budgetRemaining / 1000)}k</strong><small>after {config.weeks} weeks</small></div>
      <div><span>Run artifacts</span><strong>{scenario.event_count}</strong><small>{artifacts.root}</small></div>
    </div>
    <div className={styles.chartWrap}>
      <div className={styles.legend}>{series.map((item) => <span key={item.label}><i style={{background: item.color}}/>{item.label}</span>)}</div>
      <svg className={styles.chart} viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`Mesa resident outcomes for ${scenario.label}`}>
        {[0, 25, 50, 75, 100].map((y) => <line key={y} x1="0" x2="100" y1={y} y2={y} className={styles.gridline}/>) }
        {series.map((item) => <path key={item.label} d={pathFor(weeks, item.key, config.population)} fill="none" stroke={item.color} strokeWidth="1.8" vectorEffect="non-scaling-stroke"/>) }
      </svg>
      <div className={styles.axis}><span>Week 0</span><span>Week {config.weeks}</span></div>
    </div>
    <p className={styles.note}>Generated by the Python/Mesa source model. Rebuild with <code>generate_mesa_results.py</code>; it writes run folders plus the index consumed here.</p>
  </div>;
}
